-- Airflow ingestion using AIRFLOW_INGEST_ROLE

COPY INTO CLOUD_FINANCIAL_DB.RAW.CUSTOMERS
FROM @CLOUD_FINANCIAL_DB.RAW.S3_RAW_STAGE/customers/
FILES = ('customers.csv')
ON_ERROR = 'ABORT_STATEMENT'
FORCE = FALSE;

COPY INTO CLOUD_FINANCIAL_DB.RAW.DEALERS
FROM @CLOUD_FINANCIAL_DB.RAW.S3_RAW_STAGE/dealers/
FILES = ('dealers.csv')
ON_ERROR = 'ABORT_STATEMENT'
FORCE = FALSE;

COPY INTO CLOUD_FINANCIAL_DB.RAW.VEHICLES
FROM @CLOUD_FINANCIAL_DB.RAW.S3_RAW_STAGE/vehicles/
FILES = ('vehicles.csv')
ON_ERROR = 'ABORT_STATEMENT'
FORCE = FALSE;

COPY INTO CLOUD_FINANCIAL_DB.RAW.LOANS
FROM @CLOUD_FINANCIAL_DB.RAW.S3_RAW_STAGE/loans/
FILES = ('loans.csv')
ON_ERROR = 'ABORT_STATEMENT'
FORCE = FALSE;

COPY INTO CLOUD_FINANCIAL_DB.RAW.PAYMENTS
FROM @CLOUD_FINANCIAL_DB.RAW.S3_RAW_STAGE/payments/
FILES = ('payments.csv', 'payments_incremental_001.csv')
ON_ERROR = 'ABORT_STATEMENT'
FORCE = FALSE;