USE ROLE ACCOUNTADMIN;

USE WAREHOUSE CLOUD_FINANCIAL_WH;
USE DATABASE CLOUD_FINANCIAL_DB;
USE SCHEMA RAW;


CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID VARCHAR(20),
    CUSTOMER_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE_NUMBER VARCHAR(50),
    CITY VARCHAR(100),
    PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CREATED_DATE DATE
);


CREATE TABLE IF NOT EXISTS DEALERS (
    DEALER_ID VARCHAR(20),
    DEALER_NAME VARCHAR(200),
    DEALER_TYPE VARCHAR(50),
    CITY VARCHAR(100),
    PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    PHONE_NUMBER VARCHAR(50),
    ONBOARDING_DATE DATE,
    ACTIVE_FLAG VARCHAR(1)
);


CREATE TABLE IF NOT EXISTS VEHICLES (
    VEHICLE_ID VARCHAR(20),
    VIN VARCHAR(17),
    DEALER_ID VARCHAR(20),
    MAKE VARCHAR(100),
    MODEL VARCHAR(100),
    VEHICLE_TYPE VARCHAR(100),
    MODEL_YEAR INTEGER,
    ORIGINAL_PRICE NUMBER(12,2),
    ESTIMATED_VALUE NUMBER(12,2)
);


CREATE TABLE IF NOT EXISTS LOANS (
    LOAN_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    VEHICLE_ID VARCHAR(20),
    DEALER_ID VARCHAR(20),
    LOAN_START_DATE DATE,
    MATURITY_DATE DATE,
    ORIGINAL_PRICE NUMBER(12,2),
    DOWN_PAYMENT NUMBER(12,2),
    LOAN_AMOUNT NUMBER(12,2),
    ANNUAL_INTEREST_RATE NUMBER(5,2),
    TERM_MONTHS INTEGER,
    MONTHLY_PAYMENT NUMBER(12,2),
    LOAN_STATUS VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID VARCHAR(20),
    LOAN_ID VARCHAR(20),
    PAYMENT_NUMBER INTEGER,
    SCHEDULED_PAYMENT_DATE DATE,
    ACTUAL_PAYMENT_DATE DATE,
    SCHEDULED_AMOUNT NUMBER(12,2),
    PAYMENT_AMOUNT NUMBER(12,2),
    PAYMENT_STATUS VARCHAR(50),
    DAYS_LATE INTEGER
);

-- Verification
SHOW TABLES IN SCHEMA CLOUD_FINANCIAL_DB.RAW;