USE ROLE ACCOUNTADMIN;

USE DATABASE CLOUD_FINANCIAL_DB;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS RAW_CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS S3_RAW_STAGE
    URL = 's3://s3-bucket-name/raw/'
    STORAGE_INTEGRATION = S3_RAW_INTEGRATION
    FILE_FORMAT = RAW_CSV_FORMAT;