USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION S3_RAW_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<AWS_ROLE_ARN>'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://s3-bucket-name/raw/'
    );

-- Verification
DESC INTEGRATION S3_RAW_INTEGRATION;