USE ROLE ACCOUNTADMIN;
USE WAREHOUSE CLOUD_FINANCIAL_WH;
USE DATABASE CLOUD_FINANCIAL_DB;
USE SCHEMA RAW;


COPY INTO CUSTOMERS
FROM @S3_RAW_STAGE/customers/
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DEALERS
FROM @S3_RAW_STAGE/dealers/
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO VEHICLES
FROM @S3_RAW_STAGE/vehicles/
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO LOANS
FROM @S3_RAW_STAGE/loans/
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO PAYMENTS
FROM @S3_RAW_STAGE/payments/
ON_ERROR = 'ABORT_STATEMENT';

-- Row count validation

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CUSTOMERS
UNION ALL
SELECT 'DEALERS', COUNT(*) FROM DEALERS
UNION ALL
SELECT 'VEHICLES', COUNT(*) FROM VEHICLES
UNION ALL
SELECT 'LOANS', COUNT(*) FROM LOANS
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS;

--to check whether data looks correct
SELECT * FROM CUSTOMERS LIMIT 5;