USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DBT_TRANSFORM_ROLE
    COMMENT = 'Least-privilege role for dbt transformations';

GRANT ROLE DBT_TRANSFORM_ROLE TO USER <YOUR_SNOWFLAKE_USER>;
GRANT ROLE DBT_TRANSFORM_ROLE TO ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS CLOUD_FINANCIAL_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS CLOUD_FINANCIAL_DB.MARTS;

GRANT USAGE ON WAREHOUSE CLOUD_FINANCIAL_WH
TO ROLE DBT_TRANSFORM_ROLE;

GRANT USAGE ON DATABASE CLOUD_FINANCIAL_DB
TO ROLE DBT_TRANSFORM_ROLE;

GRANT USAGE ON SCHEMA CLOUD_FINANCIAL_DB.RAW
TO ROLE DBT_TRANSFORM_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA CLOUD_FINANCIAL_DB.RAW
TO ROLE DBT_TRANSFORM_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CLOUD_FINANCIAL_DB.RAW
TO ROLE DBT_TRANSFORM_ROLE;

GRANT USAGE ON SCHEMA CLOUD_FINANCIAL_DB.STAGING
TO ROLE DBT_TRANSFORM_ROLE;

GRANT CREATE VIEW ON SCHEMA CLOUD_FINANCIAL_DB.STAGING
TO ROLE DBT_TRANSFORM_ROLE;

GRANT CREATE TABLE ON SCHEMA CLOUD_FINANCIAL_DB.STAGING
TO ROLE DBT_TRANSFORM_ROLE;

GRANT USAGE ON SCHEMA CLOUD_FINANCIAL_DB.MARTS
TO ROLE DBT_TRANSFORM_ROLE;

GRANT CREATE VIEW ON SCHEMA CLOUD_FINANCIAL_DB.MARTS
TO ROLE DBT_TRANSFORM_ROLE;

GRANT CREATE TABLE ON SCHEMA CLOUD_FINANCIAL_DB.MARTS
TO ROLE DBT_TRANSFORM_ROLE;