USE ROLE ACCOUNTADMIN;
USE DATABASE CLOUD_FINANCIAL_DB;

CREATE SCHEMA IF NOT EXISTS HISTORY;

GRANT USAGE
ON SCHEMA CLOUD_FINANCIAL_DB.HISTORY
TO ROLE DBT_TRANSFORM_ROLE;

GRANT CREATE TABLE
ON SCHEMA CLOUD_FINANCIAL_DB.HISTORY
TO ROLE DBT_TRANSFORM_ROLE;