USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR CLOUD_FINANCIAL_MONITOR
WITH
    CREDIT_QUOTA = 5
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 80 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE OR REPLACE WAREHOUSE CLOUD_FINANCIAL_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

ALTER WAREHOUSE CLOUD_FINANCIAL_WH
SET RESOURCE_MONITOR = CLOUD_FINANCIAL_MONITOR;

CREATE DATABASE IF NOT EXISTS CLOUD_FINANCIAL_DB;

CREATE SCHEMA IF NOT EXISTS CLOUD_FINANCIAL_DB.RAW;

USE DATABASE CLOUD_FINANCIAL_DB;
USE SCHEMA RAW;

-- Verification
SHOW WAREHOUSES LIKE 'CLOUD_FINANCIAL_WH';
SHOW DATABASES LIKE 'CLOUD_FINANCIAL_DB';
SHOW SCHEMAS LIKE 'RAW' IN DATABASE CLOUD_FINANCIAL_DB;